services:
  abhyas_api:
    image: ghcr.io/vitharn-hq/abhyas:latest
    restart: always
    environment:
      - DOCKER_API_VERSION=1.40
      - NIDHI_DEV_SERVER_URL=http://100.83.65.7:8001
      - NIDHI_APP_API_KEY=super_secret_app_api_key_123
      - PROJECT_SLUG=abhyas
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - DEBUG=0
    ports:
      - "8003:8000"
