# Generated by Django 6.0.5 on 2026-05-10 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('paper_type', models.CharField(choices=[('regular', 'Regular'), ('supply', 'Supply'), ('mid', 'Mid')], max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('hashtags', models.CharField(blank=True, help_text='e.g. java, oopj', max_length=255)),
                ('file', models.FileField(upload_to='papers/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
