# Generated by Django 6.0.1 on 2026-05-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqapp', '0003_ticketreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='regulation',
            field=models.CharField(choices=[('R02', 'R02'), ('R05', 'R05'), ('R07', 'R07'), ('R09', 'R09'), ('R13', 'R13'), ('R15', 'R15'), ('R16', 'R16'), ('R18', 'R18'), ('R22', 'R22'), ('R25', 'R25')], default='R22', max_length=5),
        ),
        migrations.CreateModel(
            name='ImportantQuestionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('hashtags', models.CharField(blank=True, help_text='e.g. java, oopj', max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('regulation', models.CharField(choices=[('R02', 'R02'), ('R05', 'R05'), ('R07', 'R07'), ('R09', 'R09'), ('R13', 'R13'), ('R15', 'R15'), ('R16', 'R16'), ('R18', 'R18'), ('R22', 'R22'), ('R25', 'R25')], default='R22', max_length=5)),
                ('unit', models.IntegerField()),
                ('question_type', models.CharField(max_length=10)),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='iq/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
