# Generated by Django 6.0.1 on 2026-05-12 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqapp', '0005_sitevisit_iqdownload_iqview_paperdownload_paperview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at last login', null=True)),
                ('device_info', models.CharField(blank=True, help_text='User-Agent string from browser', max_length=512)),
                ('logged_in_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
