# Generated by Django 6.0.1 on 2026-06-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqapp', '0007_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last page request', null=True),
        ),
    ]
