# Generated by Django 6.0.1 on 2026-06-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqapp', '0008_usersession_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='device_info',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='usersession',
            name='login_count',
            field=models.IntegerField(default=0, help_text='Total number of successful logins'),
        ),
    ]
