# Generated by Django 6.0.1 on 2026-06-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyqapp', '0010_activitylog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iqdownload',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='iqview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paperdownload',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='paperview',
            unique_together=set(),
        ),
    ]
