# Generated by Django 6.0.5 on 2026-07-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqapp', '0012_increase_hashtags_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='UserIQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('hashtags', models.CharField(blank=True, max_length=255)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('regulation', models.CharField(choices=[('R02', 'R02'), ('R05', 'R05'), ('R07', 'R07'), ('R09', 'R09'), ('R13', 'R13'), ('R15', 'R15'), ('R16', 'R16'), ('R18', 'R18'), ('R22', 'R22'), ('R25', 'R25')], default='R22', max_length=5)),
                ('unit', models.IntegerField()),
                ('question_type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_iq_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iq_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserIQSubmissionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='pending_iq/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pyqapp.useriqsubmission')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='UserPYQSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('paper_type', models.CharField(max_length=10)),
                ('regulation', models.CharField(choices=[('R02', 'R02'), ('R05', 'R05'), ('R07', 'R07'), ('R09', 'R09'), ('R13', 'R13'), ('R15', 'R15'), ('R16', 'R16'), ('R18', 'R18'), ('R22', 'R22'), ('R25', 'R25')], default='R22', max_length=5)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('hashtags', models.CharField(blank=True, max_length=1000)),
                ('file', models.FileField(upload_to='pending_pyq/')),
                ('original_filename', models.CharField(max_length=255)),
                ('show_name', models.BooleanField(default=False)),
                ('display_name', models.CharField(default='SITE OWNER', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_pyq_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pyq_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
