# Generated by Django 6.0.5 on 2026-07-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyqapp', '0013_paper_display_name_useriqsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpyqsubmission',
            name='display_name',
            field=models.CharField(default='Nikhil Ravula', max_length=150),
        ),
    ]
