"""
Django settings for pyqproject project.

Generated by 'django-admin startproject' using Django 6.0.5.

Production: PythonAnywhere
NOTE: PythonAnywhere handles SSL termination at the proxy level.
      Do NOT set SECURE_SSL_REDIRECT=True or you will get redirect loops.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file (Cloudinary credentials, etc.)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, this MUST be set in the .env file.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required. Set it in .env")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Load from environment variable and add ngrok URL for development
allowed_hosts_from_env = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = allowed_hosts_from_env + (['*.ngrok-free.dev', '*.ngrok.io', '*.ngrok-free.app'] if DEBUG else [])

# CSRF_TRUSTED_ORIGINS must include both http:// and https:// schemes.
# Django checks the full Origin header (scheme + host) against this list.
_csrf_hosts = [host.strip() for host in ALLOWED_HOSTS if not host.startswith('127.') and host != 'localhost']
CSRF_TRUSTED_ORIGINS = (
    ['https://' + h for h in _csrf_hosts] +
    ['http://' + h for h in _csrf_hosts]
)

# Add ngrok for development
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        'https://*.ngrok-free.dev',
        'https://*.ngrok.io',
        'https://*.ngrok-free.app',
        'http://*.ngrok-free.dev',
        'http://*.ngrok.io',
        'http://*.ngrok-free.app',
    ]

# SameSite cookie settings — 'Lax' is the modern default and works
# correctly with standard form POSTs while still providing CSRF protection.
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'


# Application definition

INSTALLED_APPS = [
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pyqapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pyqapp.middleware.SingleDeviceLoginMiddleware',  # Single device login enforcement
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pyqproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pyqproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'  # IST (UTC+5:30)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# pyqapp/static/ is discovered automatically via APP_DIRS staticfiles finder.
# Only list extra directories here that are outside any installed app.
STATICFILES_DIRS = []
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Production static files

# Media files (Uploaded Question Papers)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ── SSL/HTTPS Security Settings ──────────────────────────────────────────────
# PythonAnywhere handles HTTPS at the proxy level.
# SECURE_SSL_REDIRECT must be False to avoid infinite redirect loops.
if not DEBUG:
    SECURE_SSL_REDIRECT = False  # PythonAnywhere handles this at proxy level
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS - tells browsers to only use HTTPS
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Security Headers
    SECURE_BROWSER_XSS_FILTER = True
    X_CONTENT_TYPE_NOSNIFF = True
else:
    # Development - no SSL enforcement
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


# ── Cloudinary Configuration ─────────────────────────────────────────────────
# Credentials are loaded from the .env file (never hardcoded).
# All FileField uploads now go to Cloudinary instead of local /media/ folder.
import cloudinary

cloudinary.config(
    cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME'),
    api_key    = os.environ.get('CLOUDINARY_API_KEY'),
    api_secret = os.environ.get('CLOUDINARY_API_SECRET'),
    secure     = True,  # Always use HTTPS URLs
    api_proxy  = os.environ.get('CLOUDINARY_API_PROXY'),  # Required for PythonAnywhere free plan
)

# Validate Cloudinary configuration in production
if not DEBUG:
    if not all([
        os.environ.get('CLOUDINARY_CLOUD_NAME'),
        os.environ.get('CLOUDINARY_API_KEY'),
        os.environ.get('CLOUDINARY_API_SECRET'),
    ]):
        raise ValueError("Cloudinary credentials not found in environment variables")

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY':    os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

# Route all file uploads through Cloudinary storage backend
# Django 6.0 uses STORAGES dict (DEFAULT_FILE_STORAGE was removed in Django 5.1)
# RawMediaCloudinaryStorage is needed for PDFs/docs (MediaCloudinaryStorage is for images only)
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.RawMediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# WORKAROUND for django-cloudinary-storage v0.3.0 crash on Django 6.0
# The package's collectstatic command looks for this deprecated setting
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Allow iframes from the same origin (needed for the PDF viewer modal)
X_FRAME_OPTIONS = 'SAMEORIGIN'


# ── File Upload Security ─────────────────────────────────────────────────────
# Maximum file size: 50MB
MAX_UPLOAD_SIZE = 50 * 1024 * 1024  # 50 MB

# Allowed file extensions for uploads
ALLOWED_UPLOAD_EXTENSIONS = {
    'pdf', 'doc', 'docx', 'txt',  # Documents
    'jpg', 'jpeg', 'png', 'gif',  # Images
}

# Device info max length (from User-Agent header)
DEVICE_INFO_MAX_LENGTH = 512

# Session key length
SESSION_KEY_LENGTH = 40

# Email configuration (for password resets and support)
if not DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
        },
        'pyqapp': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)